#!/usr/bin/env python
import roslib; roslib.load_manifest('abtr_priority')
from abtr_priority.srv import *
import rospy

argv = rospy.myargv()
if (len(argv) < 3):
	print "Usage: register command_name topic1 topic2 ..."
	exit -1

sname = argv[1] + "/register"
rospy.wait_for_service(sname, timeout = 30.0)
srv = rospy.ServiceProxy(sname, RegisterBehavior)
srv(argv[2:])

