/// \file iw_observer_node.cpp Standalone IWObserver node with rules parser.
///

#include <iw_observer/runtime.hpp>
#include <iw_observer/rules_ast.hpp>
#include <ros/ros.h>
#include "rules_parser.hpp"

// Refers to the parser function generated by Bison:
extern int yyparse();

int main(int argc, char** argv)
{
    using namespace iw_observer;

    ros::init(argc, argv, "iw_observer");
    
    if (argc < 2) {
        ROS_INFO("Parsing rules from stdin ...");
        yyparse();
        std::cerr << "yyparse done." << std::endl;
        ROS_INFO("The ruleset contains %lu rule(s).", ruleset().size());
    } else {
        ROS_INFO("Parsing rules from '%s' ...", argv[1]);
        // TODO!
    }

    ros::spin();
}

