#	!!!!	DEPRECATED	!!!
#	     USE EmoFunction

# Service to add an emotion in the relay
string name # name of emotion
emotions_msgs/Type type # information on emotion function (see below)

#string type # type of emotion (modulation or activation)
#string subtype # subtype of emotion (depends on type)
#string value # value of emotion's function
---
