#!/usr/bin/env python

import roslib; roslib.load_manifest("topic_filters_manager")
from topic_filters_manager.srv import *
import rospy
import sys

if len(sys.argv) < 2:
    print "Usage: {0} filter_name [filter-type]".format(sys.argv[0])
    exit(-1)

rospy.init_node("register_filter", anonymous=True)
rospy.wait_for_service("hbba/register_filter", timeout=5.0)

register_filter = rospy.ServiceProxy("hbba/register_filter", RegisterFilter)

if len(sys.argv) < 3:
    filter_type = "GenericDivider"
else:
    filter_type = sys.argv[2]

print "Registration of filter {0}...".format(sys.argv[1])

register_filter(sys.argv[1], filter_type)

